const KEY='demo_pos_basico_v1';
const seed={business:{name:'Dulce Momento Pastelería',address:'Av. Central 125, Puebla',phone:'222 555 0142'},users:[{id:1,name:'Administrador',role:'Administrador',pin:'1234'},{id:2,name:'Caja 1',role:'Cajero',pin:'1111'}],categories:['Pasteles','Repostería','Bebidas','Accesorios'],products:[
{id:1,name:'Pastel de chocolate',category:'Pasteles',price:420,stock:7,min:3,emoji:'🍫'},{id:2,name:'Pastel tres leches',category:'Pasteles',price:390,stock:4,min:3,emoji:'🎂'},{id:3,name:'Cheesecake',category:'Pasteles',price:360,stock:2,min:3,emoji:'🍰'},{id:4,name:'Cupcakes',category:'Repostería',price:38,stock:24,min:10,emoji:'🧁'},{id:5,name:'Gelatina',category:'Repostería',price:45,stock:12,min:6,emoji:'🍮'},{id:6,name:'Galletas',category:'Repostería',price:28,stock:35,min:12,emoji:'🍪'},{id:7,name:'Rebanada chocolate',category:'Repostería',price:65,stock:10,min:5,emoji:'🍰'},{id:8,name:'Velas número',category:'Accesorios',price:25,stock:16,min:6,emoji:'🕯️'},{id:9,name:'Decoración topper',category:'Accesorios',price:80,stock:5,min:3,emoji:'✨'},{id:10,name:'Bebida fría',category:'Bebidas',price:35,stock:18,min:8,emoji:'🥤'}],sales:[
{id:'V-1004',date:new Date(Date.now()-3600000).toISOString(),total:493,items:4,payment:'Efectivo',cashier:'Caja 1'},{id:'V-1003',date:new Date(Date.now()-7200000).toISOString(),total:420,items:1,payment:'Efectivo',cashier:'Caja 1'},{id:'V-1002',date:new Date(Date.now()-10800000).toISOString(),total:141,items:3,payment:'Efectivo',cashier:'Administrador'}],cash:{open:true,opening:800,expenses:0},settings:{tax:0,ticketNote:'Gracias por su compra. ¡Vuelva pronto!'}};
let db=load(),view='dashboard',cart=[],filterCat='Todos',search='';
function load(){const s=localStorage.getItem(KEY);if(s)return JSON.parse(s);localStorage.setItem(KEY,JSON.stringify(seed));return structuredClone(seed)}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n);
const fmt=d=>new Date(d).toLocaleString('es-MX',{dateStyle:'short',timeStyle:'short'});
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function modal(html){const b=document.createElement('div');b.className='modal-backdrop';b.innerHTML=`<div class="modal">${html}</div>`;b.onclick=e=>{if(e.target===b)b.remove()};document.body.appendChild(b);return b}
function navItems(){return [['dashboard','🏠','Inicio'],['sale','🧾','Punto de venta'],['products','🎂','Productos'],['categories','🗂️','Categorías'],['inventory','📦','Inventario'],['cash','💵','Caja'],['tickets','🎟️','Tickets'],['history','🕘','Historial'],['reports','📊','Reportes'],['users','👥','Usuarios'],['settings','⚙️','Configuración']]}
function shell(){document.getElementById('app').innerHTML=`<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">DM</div><span>${db.business.name}</span></div><div class="demo">PROTOTIPO DEMOSTRATIVO</div><div class="nav">${navItems().map(([v,i,t])=>`<button data-view="${v}" class="${view===v?'active':''}">${i} <span>${t}</span></button>`).join('')}</div></aside><main class="main"><header class="topbar"><div style="display:flex;gap:10px;align-items:center"><button class="btn mobile-menu" onclick="openMobileNav()">☰</button><h1>${navItems().find(x=>x[0]===view)?.[2]||'POS Básico'}</h1></div><div class="top-actions"><span class="badge ok"><span class="status-dot"></span>Caja abierta</span><button class="btn ghost hide-mobile" onclick="resetDemo()">Restablecer demo</button></div></header><section class="content" id="content"></section></main></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;shell();render()});render()}
function openMobileNav(){modal(`<h2>Módulos</h2><div class="stack">${navItems().map(([v,i,t])=>`<button class="btn" onclick="view='${v}';document.querySelector('.modal-backdrop').remove();shell()">${i} ${t}</button>`).join('')}</div>`)}
function resetDemo(){if(confirm('¿Restablecer todos los datos del prototipo?')){localStorage.removeItem(KEY);db=load();cart=[];shell();toast('Demo restablecida')}}
function render(){const c=document.getElementById('content');({dashboard:renderDashboard,sale:renderSale,products:renderProducts,categories:renderCategories,inventory:renderInventory,cash:renderCash,tickets:renderTickets,history:renderHistory,reports:renderReports,users:renderUsers,settings:renderSettings}[view]||renderDashboard)(c)}
function todaySales(){const d=new Date().toDateString();return db.sales.filter(s=>new Date(s.date).toDateString()===d)}
function renderDashboard(c){const sales=todaySales(),total=sales.reduce((a,b)=>a+b.total,0),items=sales.reduce((a,b)=>a+b.items,0),low=db.products.filter(p=>p.stock<=p.min);c.innerHTML=`<div class="grid cols-4"><div class="card metric"><small>Ventas del día</small><strong>${money(total)}</strong><span class="badge ok">Actualizado</span></div><div class="card metric"><small>Número de ventas</small><strong>${sales.length}</strong><span class="muted">Tickets emitidos</span></div><div class="card metric"><small>Productos vendidos</small><strong>${items}</strong><span class="muted">Unidades</span></div><div class="card metric"><small>Bajo stock</small><strong>${low.length}</strong><span class="badge ${low.length?'warn':'ok'}">Revisar</span></div></div><div class="grid cols-2" style="margin-top:16px"><div class="card"><div class="toolbar"><h3 style="margin:0;flex:1">Últimas ventas</h3><button class="btn small" onclick="view='history';shell()">Ver historial</button></div>${sales.slice(0,6).map(s=>`<div class="cart-item"><div><b>${s.id}</b><div class="muted">${fmt(s.date)} · ${s.items} productos</div></div><b>${money(s.total)}</b></div>`).join('')||'<div class="empty">Sin ventas todavía</div>'}</div><div class="card"><h3>Alertas de inventario</h3>${low.map(p=>`<div class="cart-item"><div><b>${p.name}</b><div class="muted">Mínimo ${p.min}</div></div><span class="badge danger">${p.stock} disponibles</span></div>`).join('')||'<div class="empty">Inventario saludable</div>'}</div></div>`}
function renderSale(c){const cats=['Todos',...db.categories];const prods=db.products.filter(p=>(filterCat==='Todos'||p.category===filterCat)&&p.name.toLowerCase().includes(search.toLowerCase()));const total=cart.reduce((a,i)=>a+i.price*i.qty,0);c.innerHTML=`<div class="split"><div><div class="toolbar"><input id="search" class="input" style="max-width:300px" placeholder="Buscar producto..." value="${search}">${cats.map(x=>`<button class="btn small ${filterCat===x?'primary':''}" data-cat="${x}">${x}</button>`).join('')}</div><div class="product-grid">${prods.map(p=>`<button class="product" data-product="${p.id}"><div><div style="font-size:32px">${p.emoji}</div><h3>${p.name}</h3><div class="muted">${p.stock} disponibles</div></div><div class="price">${money(p.price)}</div></button>`).join('')}</div></div><div class="card" style="align-self:start;position:sticky;top:86px"><h3>Venta actual</h3><div id="cart">${cart.map(i=>`<div class="cart-item"><div><b>${i.name}</b><div>${money(i.price)} c/u</div><button class="btn small danger" onclick="removeCart(${i.id})">Eliminar</button></div><div class="qty"><button onclick="qty(${i.id},-1)">−</button><b>${i.qty}</b><button onclick="qty(${i.id},1)">+</button></div></div>`).join('')||'<div class="empty">Agrega productos para comenzar</div>'}</div><div class="summary"><div class="summary-row"><span>Subtotal</span><b>${money(total)}</b></div><div class="summary-row total"><span>Total</span><span>${money(total)}</span></div><button class="btn primary" ${!cart.length?'disabled':''} onclick="checkout()">Cobrar venta</button><button class="btn ghost" onclick="cart=[];render()">Limpiar</button></div></div></div>`;document.getElementById('search').oninput=e=>{search=e.target.value;render()};document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{filterCat=b.dataset.cat;render()});document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>addCart(+b.dataset.product))}
function addCart(id){const p=db.products.find(x=>x.id===id);if(!p||p.stock<1)return toast('Sin existencia');const x=cart.find(i=>i.id===id);if(x){if(x.qty>=p.stock)return toast('No hay más existencia');x.qty++}else cart.push({...p,qty:1});render()}
function qty(id,d){const x=cart.find(i=>i.id===id),p=db.products.find(p=>p.id===id);if(!x)return;x.qty=Math.max(0,Math.min(p.stock,x.qty+d));if(!x.qty)cart=cart.filter(i=>i.id!==id);render()}
function removeCart(id){cart=cart.filter(i=>i.id!==id);render()}
function checkout(){const total=cart.reduce((a,i)=>a+i.price*i.qty,0);const b=modal(`<h2>Cobro en efectivo</h2><div class="grid cols-2"><div class="card"><span class="muted">Total a cobrar</span><h2>${money(total)}</h2></div><div class="field"><label>Cantidad recibida</label><input id="received" class="input" type="number" min="0" value="${Math.ceil(total/50)*50}"><div id="change" class="badge ok">Cambio: ${money(Math.ceil(total/50)*50-total)}</div></div></div><div class="toolbar" style="margin-top:18px"><button class="btn" onclick="document.querySelector('.modal-backdrop').remove()">Cancelar</button><button id="finish" class="btn primary">Finalizar venta</button></div>`);const r=b.querySelector('#received'),ch=b.querySelector('#change');r.oninput=()=>{const n=+r.value||0;ch.textContent=n>=total?`Cambio: ${money(n-total)}`:`Faltan: ${money(total-n)}`;ch.className='badge '+(n>=total?'ok':'danger')};b.querySelector('#finish').onclick=()=>{const received=+r.value||0;if(received<total)return toast('Cantidad insuficiente');const id='V-'+String(1000+db.sales.length+2);cart.forEach(i=>{const p=db.products.find(p=>p.id===i.id);p.stock-=i.qty});const sale={id,date:new Date().toISOString(),total,items:cart.reduce((a,i)=>a+i.qty,0),payment:'Efectivo',cashier:'Caja 1',received,change:received-total,detail:cart.map(i=>({name:i.name,qty:i.qty,price:i.price}))};db.sales.unshift(sale);save();cart=[];b.remove();ticketModal(sale);render()}}
function ticketModal(s){modal(`<div style="text-align:center"><h2>${db.business.name}</h2><div class="muted">${db.business.address}<br>${db.business.phone}</div><hr><b>Ticket ${s.id}</b><div class="muted">${fmt(s.date)}</div></div><div style="margin:18px 0">${(s.detail||[]).map(i=>`<div class="summary-row"><span>${i.qty} × ${i.name}</span><b>${money(i.qty*i.price)}</b></div>`).join('')||'<div class="muted">Detalle de demostración</div>'}</div><div class="summary-row total"><span>Total</span><span>${money(s.total)}</span></div>${s.received?`<div class="summary-row"><span>Recibido</span><span>${money(s.received)}</span></div><div class="summary-row"><span>Cambio</span><span>${money(s.change)}</span></div>`:''}<p class="muted" style="text-align:center">${db.settings.ticketNote}</p><button class="btn primary" style="width:100%" onclick="window.print()">Imprimir / Guardar PDF</button>`)}
function renderProducts(c){c.innerHTML=`<div class="toolbar"><button class="btn primary" onclick="productForm()">+ Nuevo producto</button><input id="psearch" class="input" style="max-width:280px" placeholder="Buscar..."></div><div class="table-wrap"><table class="table"><thead><tr><th>Producto</th><th>Categoría</th><th>Precio</th><th>Existencia</th><th>Acciones</th></tr></thead><tbody id="ptbody">${productRows(db.products)}</tbody></table></div>`;document.getElementById('psearch').oninput=e=>document.getElementById('ptbody').innerHTML=productRows(db.products.filter(p=>p.name.toLowerCase().includes(e.target.value.toLowerCase())))}
function productRows(ps){return ps.map(p=>`<tr><td>${p.emoji} <b>${p.name}</b></td><td>${p.category}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button class="btn small" onclick="productForm(${p.id})">Editar</button> <button class="btn small danger" onclick="deleteProduct(${p.id})">Eliminar</button></td></tr>`).join('')}
function productForm(id){const p=id?db.products.find(x=>x.id===id):{name:'',category:db.categories[0],price:0,stock:0,min:3,emoji:'🎂'};const b=modal(`<h2>${id?'Editar':'Nuevo'} producto</h2><div class="grid cols-2"><div class="field"><label>Nombre</label><input id="pn" class="input" value="${p.name}"></div><div class="field"><label>Categoría</label><select id="pc" class="select">${db.categories.map(x=>`<option ${x===p.category?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Precio</label><input id="pp" class="input" type="number" value="${p.price}"></div><div class="field"><label>Existencia</label><input id="ps" class="input" type="number" value="${p.stock}"></div><div class="field"><label>Stock mínimo</label><input id="pm" class="input" type="number" value="${p.min}"></div><div class="field"><label>Icono</label><input id="pe" class="input" value="${p.emoji}"></div></div><button id="savep" class="btn primary" style="margin-top:16px">Guardar</button>`);b.querySelector('#savep').onclick=()=>{const x={id:id||Date.now(),name:b.querySelector('#pn').value||'Producto',category:b.querySelector('#pc').value,price:+b.querySelector('#pp').value||0,stock:+b.querySelector('#ps').value||0,min:+b.querySelector('#pm').value||0,emoji:b.querySelector('#pe').value||'🎂'};if(id)Object.assign(db.products.find(p=>p.id===id),x);else db.products.push(x);save();b.remove();render();toast('Producto guardado')}}
function deleteProduct(id){if(confirm('¿Eliminar producto?')){db.products=db.products.filter(p=>p.id!==id);save();render()}}
function renderCategories(c){c.innerHTML=`<div class="grid cols-3">${db.categories.map(cat=>`<div class="card"><h3>${cat}</h3><div class="muted">${db.products.filter(p=>p.category===cat).length} productos</div><button class="btn small danger" style="margin-top:12px" onclick="deleteCategory('${cat}')">Eliminar</button></div>`).join('')}<button class="card" onclick="addCategory()" style="border-style:dashed;font-size:18px">＋ Agregar categoría</button></div>`}
function addCategory(){const n=prompt('Nombre de la categoría');if(n&& !db.categories.includes(n)){db.categories.push(n);save();render()}}
function deleteCategory(n){if(db.products.some(p=>p.category===n))return toast('La categoría tiene productos');db.categories=db.categories.filter(x=>x!==n);save();render()}
function renderInventory(c){const low=db.products.filter(p=>p.stock<=p.min);c.innerHTML=`<div class="toolbar"><span class="badge ${low.length?'warn':'ok'}">${low.length} alertas de bajo inventario</span><button class="btn" onclick="bulkStock()">Ajuste rápido</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Producto</th><th>Categoría</th><th>Existencia</th><th>Stock mínimo</th><th>Estado</th><th>Ajustar</th></tr></thead><tbody>${db.products.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.category}</td><td>${p.stock}</td><td>${p.min}</td><td><span class="badge ${p.stock<=p.min?'danger':'ok'}">${p.stock<=p.min?'Bajo':'Correcto'}</span></td><td><button class="btn small" onclick="adjustStock(${p.id})">Modificar</button></td></tr>`).join('')}</tbody></table></div>`}
function adjustStock(id){const p=db.products.find(x=>x.id===id),n=prompt(`Nueva existencia para ${p.name}`,p.stock);if(n!==null&&!isNaN(+n)){p.stock=Math.max(0,+n);save();render();toast('Inventario actualizado')}}
function bulkStock(){db.products.forEach(p=>{if(p.stock<=p.min)p.stock=p.min+5});save();render();toast('Stock de demo reabastecido')}
function renderCash(c){const sales=todaySales().reduce((a,b)=>a+b.total,0);c.innerHTML=`<div class="grid cols-3"><div class="card metric"><small>Fondo inicial</small><strong>${money(db.cash.opening)}</strong></div><div class="card metric"><small>Ventas en efectivo</small><strong>${money(sales)}</strong></div><div class="card metric"><small>Efectivo esperado</small><strong>${money(db.cash.opening+sales-db.cash.expenses)}</strong></div></div><div class="card" style="margin-top:16px"><h3>Estado de caja</h3><p><span class="badge ok">Abierta</span> desde 09:00 h</p><button class="btn primary" onclick="closeCash()">Realizar cierre de caja</button></div>`}
function closeCash(){const expected=db.cash.opening+todaySales().reduce((a,b)=>a+b.total,0)-db.cash.expenses;const n=prompt('Efectivo contado al cierre',expected);if(n===null)return;modal(`<h2>Cierre de caja</h2><div class="summary"><div class="summary-row"><span>Esperado</span><b>${money(expected)}</b></div><div class="summary-row"><span>Contado</span><b>${money(+n)}</b></div><div class="summary-row total"><span>Diferencia</span><span>${money(+n-expected)}</span></div></div><button class="btn primary" onclick="document.querySelector('.modal-backdrop').remove()">Aceptar</button>`)}
function renderTickets(c){c.innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Folio</th><th>Fecha</th><th>Cajero</th><th>Total</th><th>Acción</th></tr></thead><tbody>${db.sales.map(s=>`<tr><td><b>${s.id}</b></td><td>${fmt(s.date)}</td><td>${s.cashier}</td><td>${money(s.total)}</td><td><button class="btn small" onclick='ticketModal(${JSON.stringify(s).replaceAll("'","&#39;")})'>Ver ticket</button></td></tr>`).join('')}</tbody></table></div>`}
function renderHistory(c){renderTickets(c)}
function renderReports(c){const totals=db.categories.map(cat=>({cat,total:db.sales.reduce((a,s)=>a+((s.detail||[]).filter(i=>db.products.find(p=>p.name===i.name)?.category===cat).reduce((x,i)=>x+i.qty*i.price,0)),0)}));const max=Math.max(...totals.map(x=>x.total),1);c.innerHTML=`<div class="grid cols-2"><div class="card"><h3>Ventas recientes</h3><div class="chart">${db.sales.slice(0,7).reverse().map(s=>`<div class="bar" style="height:${Math.max(12,s.total/600*100)}%"><span>${Math.round(s.total)}</span></div>`).join('')}</div><div class="muted">Cada barra representa un ticket reciente.</div></div><div class="card"><h3>Ventas por categoría</h3>${totals.map(x=>`<div style="margin:12px 0"><div class="summary-row"><span>${x.cat}</span><b>${money(x.total)}</b></div><div style="height:8px;background:#eef0f6;border-radius:8px;overflow:hidden"><div style="height:100%;width:${x.total/max*100}%;background:var(--brand);border-radius:8px"></div></div></div>`).join('')}</div></div>`}
function renderUsers(c){c.innerHTML=`<div class="toolbar"><button class="btn primary" onclick="addUser()">+ Usuario</button></div><div class="grid cols-3">${db.users.map(u=>`<div class="card"><div style="font-size:32px">👤</div><h3>${u.name}</h3><span class="badge">${u.role}</span><p class="muted">PIN demo: ${u.pin}</p><button class="btn small danger" onclick="deleteUser(${u.id})">Eliminar</button></div>`).join('')}</div>`}
function addUser(){const name=prompt('Nombre');if(!name)return;db.users.push({id:Date.now(),name,role:'Cajero',pin:'1234'});save();render()}
function deleteUser(id){if(db.users.length<=1)return toast('Debe existir al menos un usuario');db.users=db.users.filter(u=>u.id!==id);save();render()}
function renderSettings(c){c.innerHTML=`<div class="card"><h3>Datos del negocio</h3><div class="grid cols-2"><div class="field"><label>Nombre</label><input id="bn" class="input" value="${db.business.name}"></div><div class="field"><label>Teléfono</label><input id="bp" class="input" value="${db.business.phone}"></div><div class="field"><label>Dirección</label><input id="ba" class="input" value="${db.business.address}"></div><div class="field"><label>Mensaje del ticket</label><input id="bt" class="input" value="${db.settings.ticketNote}"></div></div><button class="btn primary" style="margin-top:16px" onclick="saveSettings()">Guardar configuración</button></div>`}
function saveSettings(){db.business={name:document.getElementById('bn').value,address:document.getElementById('ba').value,phone:document.getElementById('bp').value};db.settings.ticketNote=document.getElementById('bt').value;save();shell();toast('Configuración guardada')}
if('serviceWorker' in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js');
shell();
